name: CI & CD - Lint, Build & Deploy SIGIC Nuxt Frontend (develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Lint Nuxt frontend code
    runs-on: ubuntu-latest
    environment: develop
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Clean package-lock.json
        run: rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  build:
    name: Build SIGIC Nuxt Frontend image (develop)
    runs-on: [self-hosted, develop]
    environment: develop
    if: github.event_name == 'push'

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAULINAPC6_PAT }}" | docker login ghcr.io -u PaulinaPC6 --password-stdin

      - name: Set variables
        id: vars
        run: |
          echo "owner=centrogeo" >> $GITHUB_OUTPUT
          echo "image=idegeo-nuxt-frontend" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "branch=develop" >> $GITHUB_OUTPUT

      - name: Set environment
        id: env
        run: |
          echo "NODE_ENV=production" >> "$GITHUB_OUTPUT"
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "NUXT_PUBLIC_BASE_URL=https://sigic.geoint.mx" >> "$GITHUB_OUTPUT"
          else            
            echo "NUXT_PUBLIC_BASE_URL=https://sigic.dev.geoint.mx" >> "$GITHUB_OUTPUT"
          fi

      - name: Build & tag Docker image
        run: |
          docker build --no-cache \
            -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }} \
            -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }} \
            -f Dockerfile .

      - name: Push image
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }}
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}

  deploy:
    needs: build
    runs-on: [self-hosted, develop]
    if: github.event_name == 'push'
    environment: develop

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAULINAPC6_PAT }}" | docker login ghcr.io -u PaulinaPC6 --password-stdin

      - name: Pull and restart frontend
        run: |
          cd /opt/sigic
          docker compose pull frontend-admin frontend-app
          docker compose up -d frontend-admin frontend-app
