name: CI & CD - Lint

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Lint Nuxt frontend code
    runs-on: ubuntu-latest
    environment: develop
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
